### ISSUE TITLE
[Feature Request] Allow for option to make panel opaque when window is maximized

### ISSUE THREAD

**Issue by feren** [germanfr/cinnamon-transparent-panels#1]
Kinda like Chrome OS's way of doing things, allow for an option to have the panel go fully opaque when a window is maximized...

**Comment by germanfr** [comment]
This is an already working feature. When a window is maximized it shows the theme background. If the theme itself was transparent already I can't do nothing.

**Comment by feren** [comment]
Also, could we have the option to define the exact transparency when there isn't a maximised window?

**Comment by feren** [comment]
@germanfr I was just thinking you could exploit semi-transparent to make it fully opaque...

**Comment by feren** [comment]
@germanfr Other than that, BEST EXTENSION BY FAR.

**Comment by feren** [comment]
@germanfr Also, is there a way for a theme-maker to customise the transparency when a window is maximised, just for this extension? As in like an optional method?

**Comment by feren** [comment]
@germanfr Hmm, been testing, and I've found something that has made me think of this question: If you were to allow to make the panel opaque regardless of theme, could there somehow be a way to place a black layer behind the panel?

**Comment by germanfr** [comment]
> Also, could we have the option to define the exact transparency when there isn't a maximised window?

This is hard, but doable. Furthermore, I thought of the possibility to define a custom color. Maybe in a future update.

> I was just thinking you could exploit semi-transparent to make it fully opaque...

This is hard, because I work with CSS properties. It's hard if not impossible to get the actual color from the background to remove the alpha channel.

> Also, is there a way for a theme-maker to customise the transparency when a window is maximised, just for this extension?

Actually yes. The themer should override the `panel-transparent` class and the user must select that option in the extension settings.

**Comment by feren** [comment]
@germanfr Would 'panel-transparent' be a duplicate version of #panel or would it be nested in #panel?

**Comment by germanfr** [comment]
@feren it would be `.panel-transparent` or `#panel.panel-transparent` if needed. They are at the same level.

**Comment by feren** [comment]
Hmm, getting no dice over here, could you check this?
```
#panel {
    background-color: rgba(0,0,0,1);
    box-shadow: inset 0 0px 0px #000;/*a little hack*/
    color: white;
    font-size: 10pt;
    font-weight: normal;
    height: 25px;
    background-blur: 2.5;
}

#panel.panel-transparent {
    background-color: rgba(0,0,0,0);
    box-shadow: inset 0 0px 0px #000;/*a little hack*/
    font-size: 10pt;
    font-weight: normal;
    height: 25px;
    background-blur: 0;
}
```

**Comment by germanfr** [comment]
Working here. Have you selected the option "defined by theme" in the extension settings? Also, try reloading the theme and the extension.

**Comment by feren** [comment]
Ah whoops, was using the wrong version of my theme, PS: Is there a way to get the gradient in the theme's CSS? (Hang on, wait, I'll find the gradient tech)

**Comment by germanfr** [comment]
Here is what I used in the extension code.
```scss
.panel-transparent {
	background-gradient-direction: vertical;
	background-gradient-start: transparent;
	background-gradient-end: rgba(0,0,0,0.4);
}
```

**Comment by feren** [comment]
@germanfr Getting this...
![screenshot from 2016-12-09 18-23-24](https://cloud.githubusercontent.com/assets/11057934/21059894/9e169a6e-be3c-11e6-91ff-e926fb73d3ef.png)

**Comment by germanfr** [comment]
You have to remove the background of #panelLeft and such. See the [stylesheet.css](https://github.com/germanfr/cinnamon-transparent-panels/blob/master/transparent-panels%40germanfr/stylesheet.css) for inspiration, but **don't** override those classes.

**Comment by feren** [comment]
@germanfr From what I can see, the only parts with a background of those things is the styling for Panel Edit Mode...

**Comment by germanfr** [comment]
@feren yes, sorry. I swapped lines when reading from your screenshot.
Try using the `#panel` with `.panel-transparent` and set the background to transparent there. Also you have to differentiate from top and bottom panels swapping the gradient start and end. 

What theme are you using?

**Comment by feren** [comment]
@germanfr Is your extension compatible with copying the whole of Transparent With Shadow to the theme itself? I tried it by replacing the older version I tried of the gradient and got no dice... I'm talking about 'panel-transparent-gradient'...

Theme I use? feren For Touch Screens WIP (One of my themes, I'm making it for feren OS to possibly add this extension into the mix in the future...)

**Comment by germanfr** [comment]
@feren no, you shouldn't copy the classes to your theme, because they won't get applied. If so, you can copy them removing the `-gradient ` part, leaving it as `panel-transparent` only.

**Comment by germanfr** [comment]
You can copy this to your theme.
```css
.panel-transparent,
#panel.panel-transparent,
.panel-transparent #panelLeft,
.panel-transparent #panelCenter,
.panel-transparent #panelRight {
	border-image: none;
	border: none;
	box-shadow: none;
	background-gradient-direction: vertical;
	background-gradient-start: transparent;
	background-gradient-end: transparent;
	background: transparent;
}

.panel-transparent,
.panel-bottom.panel-transparent,
#panel.panel-transparent {
	background-gradient-direction: vertical;
	background-gradient-start: transparent;
	background-gradient-end: rgba(0,0,0,0.4);
}

.panel-transparent-gradient.panel-top,
#panel.panel-transparent-gradient.panel-top {
	background-gradient-start: rgba(0,0,0,0.4);
	background-gradient-end: transparent;
}
```
