### ISSUE TITLE
[feature request] white shadow for light mode + automatic switching

### ISSUE THREAD

**Issue by quantenzitrone** [germanfr/cinnamon-transparent-panels#46]
```
Cinnamon version: Cinnamon 5.2.7
 ```

**White Shadow**
When using a light desktop theme (dark icons to go on a light background), the shadow makes the icons harder to see.
A white shadow would bring the same feature, as the normal shadow, to light themes.

**Automatic Switching**
When switching back and forth from light and dark mode themes, automatic switching of the shadow color would heavily reduce the time needed for switching. 
This is especially annoying if theme switching is a two click action with, for example, [this](https://cinnamon-spices.linuxmint.com/applets/view/347) applet, or even more so if the computer is configured to switch automatically at specific times.
 
**Steps to reproduce**
Use any light desktop theme like Mint-Y (not Mint-Y-Dark).

**Comment by quantenzitrone** [comment]
Sorry, I now read your comment on the last issue. 

Furthermore, I was able to solve it by copying Mint-Y-Blue and Mint-Y-Dark-Blue from /usr/share/themes to ~/.local/share/themes and modifying the cinnamon.css there. My panel has always a gradient from black/white to transparent now. 

For anyone that wants to do the same:
I changed this bit in Mint-Y-Blue:
```css
.panel-top, .panel-bottom, .panel-left, .panel-right {
  color: #ffffff;
  border: none;
  background-color: rgba(242, 242, 244, 0.99);
  font-size: 1em;
  padding: 0px; }
```
to this:
```css
.panel-top, .panel-bottom, .panel-left, .panel-right {
  color: #ffffff;
  border: none;
  background-gradient-direction: vertical;
  background-gradient-start: rgba(255,255,255,0.4);
  background-gradient-end: transparent;
  font-size: 1em;
  padding: 0px; }
```
similarly for the cinnamon.css in Mint-Y-Dark-Blue
